In [ ]:
# DO5 Logistic Regression


In [1]:
#libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns

In [3]:
dataLink ='https://raw.githubusercontent.com/DUanalytics/pyJupyter/master/data/purchaseData.csv'

In [4]:
df = pd.read_csv(dataLink)
df.shape

(19, 5)

In [5]:
df.columns

Index(['userID', 'gender', 'age', 'salary', 'purchased'], dtype='object')

In [7]:
df.describe()

userID        age         salary  purchased
count  1.900000e+01  19.000000      19.000000  19.000000
mean   1.567745e+07  29.526316   56947.368421   0.210526
std    7.151572e+04   8.852924   33569.949664   0.418854
min    1.557077e+07  18.000000   18000.000000   0.000000
25%    1.561188e+07  25.500000   27000.000000   0.000000
50%    1.569483e+07  27.000000   57000.000000   0.000000
75%    1.572804e+07  33.500000   80000.000000   0.000000
max    1.581094e+07  47.000000  150000.000000   1.000000

In [8]:
df.head()

userID  gender  age  salary  purchased
0  15624510    Male   19   19000          0
1  15810944    Male   35   20000          0
2  15668575  Female   26   43000          0
3  15603246  Female   27   57000          0
4  15804002    Male   19   76000          0

we will select numerical columns age & salary to predict if customer will buy the product(1) or not(0)

In [9]:
X = df[['age', 'salary']]
y = df.purchased
print(pd.concat([X, y], axis=1))

    age  salary  purchased
0    19   19000          0
1    35   20000          0
2    26   43000          0
3    27   57000          0
4    19   76000          0
5    27   58000          0
6    27   84000          0
7    32  150000          1
8    25   33000          0
9    35   65000          0
10   26   80000          0
11   26   52000          0
12   20   86000          0
13   32   18000          0
14   18   82000          0
15   29   80000          0
16   47   25000          1
17   45   26000          1
18   46   28000          1


In [ ]:
# Split the data into train and test

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(14, 2) (5, 2) (14,) (5,)


it is very important to perform feature scaling here because Age and Salary values lie in different ranges. If we don’t scale the features then the Salary feature will dominate the Age feature when the model finds the nearest neighbor to a data point in the data space.

In [13]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
XS_train = sc_x.fit_transform(X_train) 
XS_test = sc_x.transform(X_test)
#Age and Estimated salary features values are scaled and now there in the -1 to 1. 
#Hence, each feature will contribute equally to decision making i.e. finalizing the hypothesis. 

In [21]:
print(XS_train)
print(type(XS_train))

[[ 2.149452   -1.02601437]
 [-0.28717375  0.70708966]
 [-1.26182405  0.4720925 ]
 [-0.40900504 -0.49727077]
 [-0.28717375 -0.0566511 ]
 [ 0.32198269 -1.23163688]
 [ 0.68747655  0.14897141]
 [ 0.32198269  2.6458162 ]
 [ 1.90578942 -0.99663973]
 [-0.40900504 -0.23289897]
 [-0.28717375 -0.08602574]
 [-1.26182405 -1.20226224]
 [-0.04351117  0.58959108]
 [-1.13999276  0.76583895]]
<class 'numpy.ndarray'>


In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(XS_train, y_train)

LogisticRegression(random_state=0)

In [18]:
y_pred = classifier.predict(XS_test)

In [ ]:
#test the performance of our model – Confusion Matrix 

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[4 0]
 [0 1]]


Out of 5 : 
True Positive + True Negative = 4 + 1 
False Positive + False Negative = 0 + 0
Performance measure – Accuracy 

In [20]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  1.0


In [32]:
print(pd.concat([X_test, y_test], axis=1))
print(y_pred)

    age  salary  purchased
10   26   80000          0
1    35   20000          0
8    25   33000          0
18   46   28000          1
14   18   82000          0
[0 0 0 1 0]


XSDF_train = pd.DataFrame(XS_train, columns = ['age','salary'])
XSDF_test = pd.DataFrame(XS_test, columns = ['age','salary'])
yDF_test = pd.DataFrame(y_test, columns = ['predicted'])

In [ ]:
## using stats model

In [36]:
import statsmodels.api as sm

In [37]:
log_reg = sm.Logit(y_train, XS_train).fit()

Optimization terminated successfully.
         Current function value: 0.399719
         Iterations 7


Iterations refer to the number of times the model iterates over the data, trying to optimize the model.

In [38]:
print(log_reg.summary())

                           Logit Regression Results                           
Dep. Variable:              purchased   No. Observations:                   14
Model:                          Logit   Df Residuals:                       12
Method:                           MLE   Df Model:                            1
Date:                Sun, 26 Feb 2023   Pseudo R-squ.:                  0.2307
Time:                        19:51:04   Log-Likelihood:                -5.5961
converged:                       True   LL-Null:                       -7.2741
Covariance Type:            nonrobust   LLR p-value:                   0.06696
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             2.5989      1.467      1.772      0.076      -0.276       5.474
x2             0.7946      0.993      0.800      0.424      -1.152       2.741


Explanation of some of the terms in the summary table:
- coef : the coefficients of the independent variables in the regression equation.
- Log-Likelihood : the natural logarithm of the Maximum Likelihood Estimation(MLE) function. MLE is the optimization process of finding the set of parameters that result in the best fit.
- LL-Null : the value of log-likelihood of the model when no independent variable is included(only an intercept is included).
- Pseudo R-squ. : a substitute for the R-squared value in Least Squares linear regression. It is the ratio of the log-likelihood of the null model to that of the full model.

In [41]:
yhat = log_reg.predict(X_test)
prediction = list(map(round, yhat))
print(yhat)

10    1.0
1     1.0
8     1.0
18    1.0
14    1.0
dtype: float64


In [40]:
# comparing original and predicted values of y
print('Actual values', list(y_test.values))
print('Predictions :', prediction)

Actual values [0, 0, 0, 1, 0]
Predictions : [1, 1, 1, 1, 1]


In [ ]:
from sklearn.metrics import (confusion_matrix, accuracy_score)

In [42]:
# confusion matrix
cm = confusion_matrix(y_test, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(y_test, prediction))

Confusion Matrix : 
 [[0 4]
 [0 1]]
Test accuracy =  0.2


## end of topic
https://www.geeksforgeeks.org/ml-logistic-regression-using-python/