In [ ]:
# make data

In [6]:
import numpy as np
from sklearn.datasets import make_classification
import sys

In [7]:
np.set_printoptions(threshold=sys.maxsize)

In [13]:
np.set_printoptions(edgeitems=30, linewidth=1000,  formatter=dict(float=lambda x: "%.2g" % x))

In [14]:
X, y = make_classification(1000, 20, n_informative=10, random_state=0)
X = X.astype(np.float32)
y = y.astype(np.int64)

In [22]:
print(len(X), X)

1000 [[-0.97 -2.2 0.17 0.81 -3.4 -2.1 -0.4 2.9 -2.2 1.2 0.044 -0.52 -0.86 -1.1 0.32 -0.82 -1.1 -0.9 0.38 -1.1]
 [-0.45 4.3 -0.49 -4.9 -2.9 2.6 -2 -0.092 0.08 -0.089 -0.61 -1.1 0.49 -0.5 0.56 1 -2 2.9 -0.97 2.2]
 [0.041 -2.5 -0.27 -9 -0.76 1.1 1.4 2.6 1.2 -3.3 -0.12 0.88 1.1 0.63 -0.069 2.7 0.0048 3.4 5.6 0.37]
 [-0.52 0.51 1.5 -8.2 -2.7 -2.7 3 0.7 2.9 0.71 0.91 -0.26 -0.42 0.67 0.48 -0.23 -3.3 1.4 1.1 0.76]
 [-0.38 -4.4 -0.28 -7.4 -3.3 1.7 2.7 -0.57 1.3 0.56 1.3 -0.51 0.81 0.01 -0.72 3.3 2.1 3.9 2.7 0.99]
 [0.56 -2.8 2.9 2.7 2.1 3.4 -0.8 -0.54 -1.3 -4.5 -1.7 -0.12 2 0.8 0.68 -0.98 -1.5 1.6 2.6 0.7]
 [-0.11 -0.53 -0.21 -6 -2.5 -1.2 0.84 0.059 -0.4 0.12 -0.1 0.99 2.4 0.84 0.79 2.1 -2.3 1.4 2.3 0.66]
 [0.47 -3.7 0.98 1.2 1.5 0.54 0.29 -1.1 -0.52 0.13 1.6 0.48 0.36 -0.26 0.49 1.6 1 -0.93 2.5 0.17]
 [0.69 0.83 1.6 0.56 -3.3 -0.82 0.082 0.72 -2.6 0.036 1.7 -0.9 -0.44 1.1 -0.74 -2.9 0.04 0.36 0.93 2.1]
 [0.023 -4 0.32 -1.9 -1.9 0.27 1.4 -1.9 2.2 0.56 -1.3 -0.046 -1.5 -0.22 -0.1 -0.77 1.1 1.7 

In [21]:
print(len(y), y)

1000 [0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 

In [30]:
np.concatenate([X, y.reshape(-1,1)], axis=1)

array([[-0.97, -2.2, 0.17, 0.81, -3.4, -2.1, -0.4, 2.9, -2.2, 1.2, 0.044, -0.52, -0.86, -1.1, 0.32, -0.82, -1.1, -0.9, 0.38, -1.1, 0],
       [-0.45, 4.3, -0.49, -4.9, -2.9, 2.6, -2, -0.092, 0.08, -0.089, -0.61, -1.1, 0.49, -0.5, 0.56, 1, -2, 2.9, -0.97, 2.2, 0],
       [0.041, -2.5, -0.27, -9, -0.76, 1.1, 1.4, 2.6, 1.2, -3.3, -0.12, 0.88, 1.1, 0.63, -0.069, 2.7, 0.0048, 3.4, 5.6, 0.37, 1],
       [-0.52, 0.51, 1.5, -8.2, -2.7, -2.7, 3, 0.7, 2.9, 0.71, 0.91, -0.26, -0.42, 0.67, 0.48, -0.23, -3.3, 1.4, 1.1, 0.76, 0],
       [-0.38, -4.4, -0.28, -7.4, -3.3, 1.7, 2.7, -0.57, 1.3, 0.56, 1.3, -0.51, 0.81, 0.01, -0.72, 3.3, 2.1, 3.9, 2.7, 0.99, 1],
       [0.56, -2.8, 2.9, 2.7, 2.1, 3.4, -0.8, -0.54, -1.3, -4.5, -1.7, -0.12, 2, 0.8, 0.68, -0.98, -1.5, 1.6, 2.6, 0.7, 1],
       [-0.11, -0.53, -0.21, -6, -2.5, -1.2, 0.84, 0.059, -0.4, 0.12, -0.1, 0.99, 2.4, 0.84, 0.79, 2.1, -2.3, 1.4, 2.3, 0.66, 0],
       [0.47, -3.7, 0.98, 1.2, 1.5, 0.54, 0.29, -1.1, -0.52, 0.13, 1.6, 0.48, 0.36, -0.26, 0.49

In [29]:
np.vstack((X, y.reshape(-1,1)))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 20 and the array at index 1 has size 1

In [31]:
np.column_stack((X, y))

array([[-0.97, -2.2, 0.17, 0.81, -3.4, -2.1, -0.4, 2.9, -2.2, 1.2, 0.044, -0.52, -0.86, -1.1, 0.32, -0.82, -1.1, -0.9, 0.38, -1.1, 0],
       [-0.45, 4.3, -0.49, -4.9, -2.9, 2.6, -2, -0.092, 0.08, -0.089, -0.61, -1.1, 0.49, -0.5, 0.56, 1, -2, 2.9, -0.97, 2.2, 0],
       [0.041, -2.5, -0.27, -9, -0.76, 1.1, 1.4, 2.6, 1.2, -3.3, -0.12, 0.88, 1.1, 0.63, -0.069, 2.7, 0.0048, 3.4, 5.6, 0.37, 1],
       [-0.52, 0.51, 1.5, -8.2, -2.7, -2.7, 3, 0.7, 2.9, 0.71, 0.91, -0.26, -0.42, 0.67, 0.48, -0.23, -3.3, 1.4, 1.1, 0.76, 0],
       [-0.38, -4.4, -0.28, -7.4, -3.3, 1.7, 2.7, -0.57, 1.3, 0.56, 1.3, -0.51, 0.81, 0.01, -0.72, 3.3, 2.1, 3.9, 2.7, 0.99, 1],
       [0.56, -2.8, 2.9, 2.7, 2.1, 3.4, -0.8, -0.54, -1.3, -4.5, -1.7, -0.12, 2, 0.8, 0.68, -0.98, -1.5, 1.6, 2.6, 0.7, 1],
       [-0.11, -0.53, -0.21, -6, -2.5, -1.2, 0.84, 0.059, -0.4, 0.12, -0.1, 0.99, 2.4, 0.84, 0.79, 2.1, -2.3, 1.4, 2.3, 0.66, 0],
       [0.47, -3.7, 0.98, 1.2, 1.5, 0.54, 0.29, -1.1, -0.52, 0.13, 1.6, 0.48, 0.36, -0.26, 0.49