# Numpy
NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.
For example, the array for the coordinates of a point in 3D space, [1, 2, 1], has one axis. That axis has 3 elements in it, so we say it has a length of 3. 
https://numpy.org/doc/stable/user/whatisnumpy.html
NumPy gives us the best of both worlds: element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code
Why is NumPy Fast?
https://numpy.org/doc/stable/user/quickstart.html
Understand the difference between one-, two- and n-dimensional arrays in NumPy;
Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;
Understand axis and shape properties for n-dimensional arrays. 

In [1]:
# Library
import numpy as np
import random as rg

In [2]:
# Create array - 1D
a = np.array([2, 3, 4])
print(a, '\t', type(a), '\t', a.dtype, a.shape)

[2 3 4] 	 <class 'numpy.ndarray'> 	 int32 (3,)


In [3]:
# 2D array
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b, '\t', type(b), '\t', b.dtype, b.shape)

[[1.5 2.  3. ]
 [4.  5.  6. ]] 	 <class 'numpy.ndarray'> 	 float64 (2, 3)


In [4]:
# 2D array complex type
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c, '\t', type(c), '\t', c.dtype, c.shape)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]] 	 <class 'numpy.ndarray'> 	 complex128 (2, 2)


In [5]:
# zero values array
#Often, the elements of an array are originally unknown, but its size is known. 
#Hence, NumPy offers several functions to create arrays with initial placeholder content. 
#These minimize the necessity of growing arrays, an expensive operation.
# The function zeros creates an array full of zeros, the function ones creates an array full of ones, 
#and the function empty creates an array whose initial content is random and depends on the state of the memory. 
#By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
np.empty((2, 3))  # any default values

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
## Sequence of values
# the arange function which is analogous to the Python built-in range, but returns an array.
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [9]:
np.arange(0, 2, 0.3)
#When arange is used with floating point arguments, 
#it is generally not possible to predict the number of elements obtained, 
#due to the finite floating point precision. For this reason, it is usually better to use the
#function linspace that receives as an argument the number of elements that we want,
#instead of the step:

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [10]:
np.linspace(0, 2, 9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Display
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

## Random Values

In [11]:
rg = np.random.default_rng(1)
print(rg)  #random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))  #same values becoz of rg
print(rg, '\n', a, '\n',b)

Generator(PCG64)
Generator(PCG64) 
 [[1 1 1]
 [1 1 1]] 
 [[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [12]:
a = rg.random((2, 3))
print(a)

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]


## Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
x[1, 2, ...] is equivalent to x[1, 2, :, :, :], #mutli dim
x[..., 3] to x[:, :, :, :, 3] and
x[4, ..., 5, :] to x[4, :, :, 5, :].

In [13]:
a = np.arange(10)**3
print(a, '\n')
# Indexing
print(a[2], '\t', a[2:5])

[  0   1   8  27  64 125 216 343 512 729] 

8 	 [ 8 27 64]


In [14]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print(a)

[1000    1 1000   27 1000  125  216  343  512  729]


In [18]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

## Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [12]:
B = np.arange(3)
print(np.exp(B), '\n', np.sqrt(B))

[1.         2.71828183 7.3890561 ] 
 [0.         1.         1.41421356]


In [ ]:
## Reshape
Change Dimension of Numpy Array

In [4]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Summary

In [6]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [8]:
b.sum(axis=1)

array([ 6, 22, 38])

In [11]:
print(b.min(axis=0), '\t', b.min(axis=1))
print(b.max(axis=0), '\t', b.max(axis=1))      

[0 1 2 3] 	 [0 4 8]
[ 8  9 10 11] 	 [ 3  7 11]


## Line Space
Divide range of values by certain number of divisions

In [3]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

## Reshape

In [36]:
a = np.floor(10 * rg.random((3, 4)))
print(a)

[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]


In [37]:
a.ravel()  # returns the array, flattened

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [38]:
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [39]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [41]:
print(a.shape, '\t', a.ravel().shape, '\t', a.T.shape)

(3, 4) 	 (12,) 	 (4, 3)


In [45]:
a.resize((2, 6))
print(a)

[[3. 7. 3. 4. 1. 4.]
 [2. 2. 7. 2. 4. 9.]]


In [46]:
# with -1 value in shape
#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
a.reshape(3, -1)  # fix rows, columns automatically calculated

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [47]:
a.reshape(-1, 2)  # fix cols, rows automatically calculated

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

## Stack
hstack, vstack

In [48]:
a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))
print(a, '\t', b)

[[9. 7.]
 [5. 2.]] 	 [[1. 9.]
 [5. 1.]]


In [49]:
np.vstack((a, b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [50]:
np.hstack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [51]:
# The function column_stack stacks 1D arrays as columns into a 2D array. 
#It is equivalent to hstack only for 2D arrays:
np.column_stack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [54]:
# newexis
a[:, np.newaxis]  # view `a` as a 2D column vector

array([[[9., 7.]],

       [[5., 2.]]])

In [55]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[[9., 7.],
        [1., 9.]],

       [[5., 2.],
        [5., 1.]]])

In [ ]:
#function row_stack is equivalent to vstack for any input arrays. In fact, row_stack is an alias for vstack:

In [57]:
#n complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. 
#They allow the use of range literals
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

## Numpy and Matlab
https://numpy.org/doc/stable/user/numpy-for-matlab-users.html
rough equivalents for some common MATLAB expressions

In [ ]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import eigs

### Useful np functions

Array Creation - arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

Conversions -ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

Manipulations - array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

Questions - all, any, nonzero, where

Ordering - argmax, argmin, argsort, max, min, ptp, searchsorted, sort

Operations - choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

Basic Statistics - cov, mean, std, var

Basic Linear Algebra - cross, dot, outer, linalg.svd, vdot